const comments = [
    {
        "id": 24930,
        "content": "<p>Test</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-24 02:10:29",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 4,
        "special": "Дастурчи",
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": [
            {
                "id": 24983,
                "content": "Assalomu alaykum",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": true,
                "reason_to_hide": "Ta'qiqlangan matn",
                "created_at": "2020-09-09 11:22:09",
                "special": "Журналист/блогер"
            },
            {
                "id": 24984,
                "content": "keyingi javob",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:23:01",
                "special": null
            },
            {
                "id": 24990,
                "content": "reply and scroll immediately",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:43:09",
                "special": null
            },
            {
                "id": 24991,
                "content": "scroll testing",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:43:39",
                "special": null
            },
            {
                "id": 24992,
                "content": "scroll test",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:44:02",
                "special": null
            },
            {
                "id": 24993,
                "content": "scroll 50px",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:44:29",
                "special": null
            },
            {
                "id": 24994,
                "content": "scroll 150",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:45:14",
                "special": null
            },
            {
                "id": 24998,
                "content": "scroll",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:52:43",
                "special": null
            },
            {
                "id": 24999,
                "content": "$('#answer-box-' + data['id']).scrollTo();\n",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:53:15",
                "special": null
            },
            {
                "id": 25000,
                "content": "$('#answer-box-' + data['id']).scrollTo();\n",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:53:32",
                "special": null
            },
            {
                "id": 25001,
                "content": "scrollTop",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:55:44",
                "special": null
            },
            {
                "id": 25002,
                "content": "scrollTo('#answer-box-' + data['id'])",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:58:27",
                "special": null
            },
            {
                "id": 25003,
                "content": "yaxshi scroll",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:00:41",
                "special": null
            },
            {
                "id": 25004,
                "content": "Yomon scroll",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:02:15",
                "special": null
            },
            {
                "id": 25005,
                "content": "\\\\\\$('.comment-area-' + data['entity_id']).getNiceScroll(0).doScrollTop($('#answer-box-' + data['id']).height());\n",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:06:35",
                "special": null
            },
            {
                "id": 25007,
                "content": "sdfsd ds",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:12:28",
                "special": null
            },
            {
                "id": 25008,
                "content": "$('.comment-area-' + data['entity_id']).getNiceScroll(0).doScrollTop(parentLi.height() - $('#answer-box-' + data['id']).height());\n",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:13:15",
                "special": null
            },
            {
                "id": 25010,
                "content": "test",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:14:07",
                "special": null
            },
            {
                "id": 25016,
                "content": "javob 14.09.2020\n",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-14 20:17:46",
                "special": null
            },
            {
                "id": 25035,
                "content": "reply",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-26 12:40:31.474855",
                "special": null
            }
        ]
    },
    {
        "id": 24931,
        "content": "<p>1 comment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 148533,
        "parent_id": null,
        "created_at": "2020-08-24 12:35:30",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": true,
        "support_count": 2,
        "special": null,
        "is_hidden": true,
        "reason_to_hide": "Yoqmadi",
        "file": null,
        "is_supported": true,
        "authority_answers": [
            {
                "content": "<p>1 comment ga javob</p>\r\n",
                "created_at": "2020-09-09 14:37:44",
                "authority": "Министерство юстиции Республики Узбекистан"
            }
        ],
        "user_answers": [
            {
                "id": 24985,
                "content": "1 comment ga javob ishla yaxshimi?\nXullash hammasi yaxshi",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:37:17",
                "special": null
            },
            {
                "id": 24986,
                "content": "1 comment ga 2- javob ishla yaxshimi? Xullas hammasi yaxshi\nscroll top ishlamayapti",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:38:02",
                "special": null
            },
            {
                "id": 24988,
                "content": "1 commentga javob\nScroll top ishlashi kerak",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:41:47",
                "special": null
            },
            {
                "id": 24989,
                "content": "test scroll top",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:42:06",
                "special": null
            },
            {
                "id": 24997,
                "content": "scroll again",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:50:39",
                "special": null
            },
            {
                "id": 25011,
                "content": "test 222",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:14:19",
                "special": null
            }
        ]
    },
    {
        "id": 24932,
        "content": "<p>2-comment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 148536,
        "parent_id": null,
        "created_at": "2020-08-24 12:35:50",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 3,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": [
            {
                "id": 24995,
                "content": "scroll -200",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:45:49",
                "special": null
            }
        ]
    },
    {
        "id": 24933,
        "content": "<p>2.1 komment</p>",
        "full_name": "Аноним",
        "document_id": 14158,
        "entity_id": 148536,
        "parent_id": null,
        "created_at": "2020-08-24 12:35:58",
        "authority": null,
        "is_anonymous": true,
        "is_applied": false,
        "is_answered": false,
        "support_count": 3,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": [
            {
                "id": 24996,
                "content": "new commeny",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 11:47:11",
                "special": null
            }
        ]
    },
    {
        "id": 24934,
        "content": "<p>3-komment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 148539,
        "parent_id": null,
        "created_at": "2020-08-24 12:36:15",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 3,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": [
            {
                "id": 25006,
                "content": "5646132 $('.comment-area-' + data['entity_id']).getNiceScroll(0).doScrollTop($('#answer-box-' + data['id']).height());\n",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:07:04",
                "special": null
            }
        ]
    },
    {
        "id": 24935,
        "content": "<p>3.1 komment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 148539,
        "parent_id": null,
        "created_at": "2020-08-24 12:36:22",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 3,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24936,
        "content": "<p>3.2 komment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 148539,
        "parent_id": null,
        "created_at": "2020-08-24 12:36:28",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24937,
        "content": "<p>Hujjatga komment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-24 12:36:45",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": true,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [
            {
                "content": "<p>Hujjatga kommentga javob</p>\r\n",
                "created_at": "2020-09-09 14:40:13",
                "authority": "Министерство юстиции Республики Узбекистан"
            }
        ],
        "user_answers": []
    },
    {
        "id": 24938,
        "content": "<p>Hujjatga komment 2</p><p>В связи с этим подготовлены опытные образцы специальных автомобилей на шасси разработки «Volkswagen», «Škoda» и «Isuzu».\r</p><p>Шавкат Мирзиёев подчеркнул важность освоения нового сегмента для замещения импорта и наращивания экспорта, а также дал необходимые указания ответственным лицам.\r</p><p>Начать сборку представленных автомобилей намечено в IV квартале текущего года на Джизакском автомобильном заводе. В 2022 году планируется освоить полный цикл производства.</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-24 12:37:37",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 2,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24939,
        "content": "<p>Hujjatga komment 3\n</p><p>В связи с этим подготовлены опытные образцы специальных автомобилей на шасси разработки «Volkswagen», «Škoda» и «Isuzu».\n</p><p>Шавкат Мирзиёев подчеркнул важность освоения нового сегмента для замещения импорта и наращивания экспорта, а также дал необходимые указания ответственным лицам.</p><p>Начать сборку представленных автомобилей намечено в IV квартале текущего года на Джизакском автомобильном заводе. В 2022 году планируется освоить полный цикл производства.</p><p>Шавкат Мирзиёев подчеркнул важность освоения нового сегмента для замещения импорта и наращивания экспорта, а также дал необходимые указания ответственным лицам.\r</p><p>\r</p><p>Начать сборку представленных автомобилей намечено в IV квартале текущего года на Джизакском автомобильном заводе. В 2022 году планируется освоить полный цикл производства.</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-24 12:38:12",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24940,
        "content": "<p>Assalomu alaykum</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:09:17",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24941,
        "content": "<p>Assalom</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:47:04",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24942,
        "content": "<p>Assalom</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:48:26",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24943,
        "content": "<p>Assalom 3</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:48:48",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24944,
        "content": "<p>Assalom 4</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:49:47",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24945,
        "content": "<p>Assalom 4</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:50:09",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24946,
        "content": "<p>Assalom 5</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:50:47",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24947,
        "content": "<p>test</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:52:16",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24948,
        "content": "<p>Шавкат Мирзиёев подчеркнул важность освоения нового сегмента для замещения импорта и наращивания экспорта, а также дал необходимые указания ответственным лицам.\r</p><p>\r</p><p>Начать сборку представленных автомобилей намечено в IV квартале текущего года на Джизакском автомобильном заводе. В 2022 году планируется освоить полный цикл производства.\r</p><p>\r</p><p>Шавкат Мирзиёев подчеркнул важность освоения нового сегмента для замещения импорта и наращивания экспорта, а также дал необходимые указания ответственным лицам.Шавкат Мирзиёев подчеркнул важность освоения нового сегмента для замещения импорта и наращивания экспорта, а также дал необходимые указания ответственным лицам.\r</p><p>\r</p><p>Начать сборку представленных автомобилей намечено в IV квартале текущего года на Джизакском автомобильном заводе. В 2022 году планируется освоить полный цикл производства.\r</p><p>\r</p><p>Шавкат Мирзиёев подчеркнул важность освоения нового сегмента для замещения импорта и наращивания экспорта, а также дал необходимые указания ответственным лицам.Шавкат Мир</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:54:04",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24949,
        "content": "<p>sdf sadfsd f</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:54:35",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24950,
        "content": "<p>&nbsp;asd asd asd asd as asd ghj&nbsp;</p><p>&nbsp;ghkl</p><p>lknf jg</p><p>f gh</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 01:54:57",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24951,
        "content": "<p>Auto scroll</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:03:32",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24952,
        "content": "<p>Auto scroll\r 2</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:05:01",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24953,
        "content": "<p>&nbsp;asd asd asd </p><p>asd as asd ghj \r</p><p><br></p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:05:33",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24954,
        "content": "<p>Auto scroll next</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:06:41",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24955,
        "content": "<p>sd asd asd\r</p><p>asd as asd ghj\r</p><p>Количество голосов: 0&nbsp;<br></p><p>OBIDOV ABRORXON ABDULLO O‘G‘LI2020-08-27 02:06:41\r</p><p>Auto scroll next</p><p>&lt;input type=\"file\"&gt;</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:07:25",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24956,
        "content": "<p>27-comment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:12:08",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24957,
        "content": "<p>28-comment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:13:19",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24958,
        "content": "29-comment",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:15:33",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24959,
        "content": "<p>30-comment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:15:44",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24960,
        "content": "<p>31</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:17:12",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24961,
        "content": "<p>32</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:19:05",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24962,
        "content": "<p>33</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:19:09",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24963,
        "content": "<p>34</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:19:13",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24964,
        "content": "<p>35</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:19:22",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24965,
        "content": "<p>36</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:23:13",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24966,
        "content": "<p>37</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:23:23",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24967,
        "content": "<p>38</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:46:44",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24968,
        "content": "<p>39</p><p><br></p><hr><p><br></p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:47:58",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24969,
        "content": "<p>40</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-27 02:49:32",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24970,
        "content": "<p>check comment datas</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-28 00:13:45",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": [
            {
                "id": 25009,
                "content": "               sdasdsa $('.comment-area-' + data['entity_id']).getNiceScroll(0).doScrollTop(parentLi.height() - $('#answer-box-' + data['id']).height());\n",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-09 12:13:34",
                "special": null
            }
        ]
    },
    {
        "id": 24971,
        "content": "<p>42 - taklif</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-29 12:21:12",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24972,
        "content": "<p>43 taklif</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-08-29 12:50:01",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24977,
        "content": "<p>44 - komment<br>Mannop akadan</p><p><b>Bold</b></p><p><i>Italic</i></p><p><u>Underline</u></p>",
        "full_name": "Аноним",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-08 20:19:15",
        "authority": null,
        "is_anonymous": true,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24978,
        "content": "<p>45 - komment\r</p><p>Mannop akadan\r</p><p><b>\rBold&nbsp;</b></p><p><i>Italic&nbsp;</i><br></p><p><u>Underline</u><br></p>",
        "full_name": "Аноним",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-08 20:22:49",
        "authority": null,
        "is_anonymous": true,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24979,
        "content": "<p>46 - komment\r</p><p>\rAbrorxon&nbsp;</p><p>\r<b>Bold&nbsp;&nbsp;</b></p><p>\r<i>Italic&nbsp;&nbsp;</i></p><p>\r<u>Underline</u></p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-08 20:24:36",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24980,
        "content": "<p>test yangi kommentda javob berish button qo'shiladimi?</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-08 21:06:18",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 24987,
        "content": "<p>salom</p><p>Scroll top ishlayaptimi?</p><p><br></p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-09 11:39:04",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25012,
        "content": "<p>new main comment</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-09 12:16:46",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25015,
        "content": "<p>Send comment without yii.getCsrfToken()</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-14 20:08:22",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25020,
        "content": "&lt;p&gt;test created at&lt;/p&gt;",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-14 20:30:21",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25017,
        "content": "<p>&lt;input type=\"file\"&gt;</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-14 20:30:21",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": [
            {
                "id": 25018,
                "content": "&lt;input type=&quot;file&quot;&gt;",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-14 20:30:51",
                "special": null
            },
            {
                "id": 25019,
                "content": "&lt;input type=&quot;file&quot;&gt;",
                "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
                "is_hidden": false,
                "reason_to_hide": null,
                "created_at": "2020-09-14 20:31:35",
                "special": null
            }
        ]
    },
    {
        "id": 25021,
        "content": "&lt;p&gt;Comment&lt;/p&gt;&lt;p&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; url: ajaxControllerUrl('send-comment'),\r&lt;/p&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:40:47",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25022,
        "content": "&lt;p&gt;komment&lt;/p&gt;&lt;p&gt;with date&lt;/p&gt;",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:41:08",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25023,
        "content": "&lt;p&gt;comment\r with date 2&lt;/p&gt;",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:42:10",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25024,
        "content": "&lt;p&gt;comment date&lt;/p&gt;",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:46:23",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25025,
        "content": "&lt;p&gt;comment with date&lt;/p&gt;",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:53:02",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25026,
        "content": "&lt;p&gt;comment with date&lt;/p&gt;",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:53:21",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25027,
        "content": "asdas as&nbsp;asdasd as d",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:55:48",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25028,
        "content": "svsdvsdvsdvsdsdvsdvsd",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:56:21",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25029,
        "content": "<p>a <b>sdsa </b>das&nbsp;</p><p>&nbsp;as <i>das</i></p><p>&nbsp;<u>asd </u>as</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:58:41",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25030,
        "content": "<p>&lt;input&gt;</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:59:00",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25031,
        "content": "<p>&lt;script&gt;</p>",
        "full_name": "OBIDOV ABRORXON ABDULLO O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-09-15 10:59:13",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": true,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25040,
        "content": "Isokov Abdulaziz",
        "full_name": "ISOKOV ABDULAZIZXON XABIBULLOXON O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-10-02 15:20:35",
        "authority": null,
        "is_anonymous": false,
        "is_applied": false,
        "is_answered": false,
        "support_count": 1,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25039,
        "content": "<p>test</p>",
        "full_name": "Аноним",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-10-02 15:20:35",
        "authority": null,
        "is_anonymous": true,
        "is_applied": false,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25041,
        "content": "<p>test 7272</p>",
        "full_name": "Аноним",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-10-03 22:19:06",
        "authority": null,
        "is_anonymous": true,
        "is_applied": true,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    },
    {
        "id": 25080,
        "content": "<p>test comment&nbsp;</p>",
        "full_name": "ISOKOV ABDULAZIZXON XABIBULLOXON O‘G‘LI",
        "document_id": 14158,
        "entity_id": 14158,
        "parent_id": null,
        "created_at": "2020-10-19 12:15:52",
        "authority": null,
        "is_anonymous": false,
        "is_applied": true,
        "is_answered": false,
        "support_count": 0,
        "special": null,
        "is_hidden": false,
        "reason_to_hide": null,
        "file": null,
        "is_supported": false,
        "authority_answers": [],
        "user_answers": []
    }
];

export default comments;